.github/workflows/promote.yml
version.properties

Try add stacktrace and rebuild branch SDKTECHNO-47 to investigate on promote failure.
Use of a new branch because #105 failed to merge has it already have been merged .
Should close #106 .

Sdktechno 49

---

build.gradle.kts

[SDKTECHNO]  use technology plugin 1.2.4

---

technologies/app/docker/metadata.yaml

Try hotfix broken promote.
This PR use a minor/useless change/commit to force re run the Promote action

[hotfix] .

---

technologies/job/spark/metadata.yaml
technologies/job/spark/spark-2.4/innerContexts/python/Dockerfile
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-2.7/build.gradle.kts
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-2.7/dockerInfo.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-2.7/image_test.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.5/build.gradle.kts
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.5/dockerInfo.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.5/image_test.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.6/build.gradle.kts
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.6/dockerInfo.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.6/image_test.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.7/build.gradle.kts
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.7/dockerInfo.yaml
technologies/job/spark/spark-2.4/innerContexts/python/spark-2.4-python-3.7/image_test.yaml
technologies/job/spark/spark-3.0/innerContexts/python/Dockerfile
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.5/build.gradle.kts
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.5/dockerInfo.yaml
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.5/image_test.yaml
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.6/build.gradle.kts
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.6/dockerInfo.yaml
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.6/image_test.yaml
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.7/build.gradle.kts
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.7/dockerInfo.yaml
technologies/job/spark/spark-3.0/innerContexts/python/spark-3.0-python-3.7/image_test.yaml
version.properties

remove references/tests to pip.conf and nexus
Closes #171

[SDKTECHNO-71][pyspark] use post SDK migration python base images

---

technologies/app/rstudio-3.6.2/metadata.yaml
technologies/app/rstudio-3.6.2/rstudio-3.6.2/Dockerfile
technologies/app/rstudio-3.6.2/rstudio-3.6.2/dockerInfo.yaml
version.properties

Following failed promote of app rstudio - attemps to re run it after some minor refacto.
Closes #142

Attempt to re-promote AppRStudio 

---

technologies/job/r/metadata.yaml
technologies/job/r/r-3.4.4-base/Dockerfile
technologies/job/r/r-3.4.4-base/dockerInfo.yaml
technologies/job/r/r-3.4.4/Dockerfile
technologies/job/r/r-3.4.4/dockerInfo.yaml
technologies/job/r/r-3.5.3-base/Dockerfile
technologies/job/r/r-3.5.3-base/dockerInfo.yaml
technologies/job/r/r-3.5.3/Dockerfile
technologies/job/r/r-3.5.3/dockerInfo.yaml
technologies/job/r/r-3.6.2-base/Dockerfile
technologies/job/r/r-3.6.2-base/dockerInfo.yaml
technologies/job/r/r-3.6.2/Dockerfile
technologies/job/r/r-3.6.2/dockerInfo.yaml
technologies/job/r/r-3.6.3-base/Dockerfile
technologies/job/r/r-3.6.3-base/dockerInfo.yaml
technologies/job/r/r-3.6.3/Dockerfile
technologies/job/r/r-3.6.3/dockerInfo.yaml
technologies/job/r/r-4.0-base/Dockerfile
technologies/job/r/r-4.0-base/dockerInfo.yaml
technologies/job/r/r-4.0/Dockerfile
technologies/job/r/r-4.0/dockerInfo.yaml
version.properties

[SDKTECHNO-90] convert UTF-32 into UTF-16 in cloudera impala configuration for R jobs

---

technologies/app/jupyspark/jupyter-spark/Dockerfile
technologies/app/jupyspark/jupyter-spark/dockerInfo.yaml
technologies/app/jupyspark/metadata.yaml
version.properties

[SDKTECHNO-68] Add scala kernel to jupyspark

---

technologies/app/jupyspark/jupyter-spark/Dockerfile
technologies/app/jupyspark/jupyter-spark/dockerInfo.yaml
technologies/app/jupyspark/metadata.yaml
technologies/app/jupyter/jupyter-base/Dockerfile
technologies/app/jupyter/jupyter-base/dockerInfo.yaml
technologies/app/jupyter/jupyter-minimal/Dockerfile
technologies/app/jupyter/jupyter-minimal/dockerInfo.yaml
technologies/app/jupyter/metadata.yaml
version.properties

[SDKTECHNO-68] adjust default images versions

---

technologies/app/jupyspark/jupyter-spark/Dockerfile
technologies/app/jupyspark/jupyter-spark/dockerInfo.yaml
technologies/app/jupyspark/metadata.yaml
technologies/app/jupyter/jupyter-base/Dockerfile
technologies/app/jupyter/jupyter-base/dockerInfo.yaml
technologies/app/jupyter/jupyter-minimal/Dockerfile
technologies/app/jupyter/jupyter-minimal/dockerInfo.yaml
technologies/app/jupyter/metadata.yaml
version.properties

[SDKTECHNO-68] force rebuild as previous promote failed

---

technologies/app/cloudbeaver/cloudbeaver-1.2.0/Dockerfile
technologies/app/cloudbeaver/cloudbeaver-1.2.0/build.gradle.kts
technologies/app/cloudbeaver/cloudbeaver-1.2.0/context.yaml
technologies/app/cloudbeaver/cloudbeaver-1.2.0/dockerInfo.yaml
technologies/app/cloudbeaver/cloudbeaver-1.2.0/image_test.yaml
technologies/app/cloudbeaver/cloudbeaver-1.2.0/resources/entrypoint.sh
technologies/app/cloudbeaver/cloudbeaver-1.2.0/resources/nginx.conf
technologies/app/cloudbeaver/dockerhub.md
technologies/app/cloudbeaver/metadata.yaml
technologies/app/cloudbeaver/technology.yaml
version.properties

[SDKTECHNO-82] Add Cloudbeaver App

---

technologies/app/rstudio-3.4.2/rstudio-3.4.2/Dockerfile
technologies/app/rstudio-3.4.2/rstudio-3.4.2/dockerInfo.yaml
technologies/app/rstudio-3.4.2/rstudio-3.4.2/image_test.yaml
technologies/app/rstudio-3.6.2/rstudio-3.6.2/Dockerfile
technologies/app/rstudio-3.6.2/rstudio-3.6.2/dockerInfo.yaml
technologies/app/rstudio-3.6.2/rstudio-3.6.2/image_test.yaml
technologies/job/r/metadata.yaml
technologies/job/r/r-3.4.4/Dockerfile
technologies/job/r/r-3.4.4/dockerInfo.yaml
technologies/job/r/r-3.4.4/image_test.yaml
technologies/job/r/r-3.5.3/Dockerfile
technologies/job/r/r-3.5.3/dockerInfo.yaml
technologies/job/r/r-3.5.3/image_test.yaml
technologies/job/r/r-3.6.2/dockerInfo.yaml
technologies/job/r/r-3.6.2/image_test.yaml
technologies/job/r/r-3.6.2/resources/requirements-bin.txt
technologies/job/r/r-3.6.3/dockerInfo.yaml
technologies/job/r/r-3.6.3/image_test.yaml
technologies/job/r/r-3.6.3/resources/requirements-bin.txt
technologies/job/r/r-3.6.3/resources/requirements-src.R
technologies/job/r/r-4.0/dockerInfo.yaml
technologies/job/r/r-4.0/image_test.yaml
technologies/job/r/r-4.0/resources/requirements-bin.txt
technologies/job/r/r-4.0/resources/requirements-src.R
version.properties

[SDKTECHNO-91] add aws.s3 lib to R and RStudio images

---

technologies/app/rstudio-4.1/README.md
technologies/app/rstudio-4.1/dockerhub.md
technologies/app/rstudio-4.1/metadata.yaml
technologies/app/rstudio-4.1/rstudio-4.1/Dockerfile
technologies/app/rstudio-4.1/rstudio-4.1/build.gradle.kts
technologies/app/rstudio-4.1/rstudio-4.1/context.yaml
technologies/app/rstudio-4.1/rstudio-4.1/dockerInfo.yaml
technologies/app/rstudio-4.1/rstudio-4.1/image_test.yaml
technologies/app/rstudio-4.1/rstudio-4.1/resources/entrypoint.sh
technologies/app/rstudio-4.1/rstudio-4.1/resources/init_rstudio.sh
technologies/app/rstudio-4.1/rstudio-4.1/resources/server.conf
technologies/app/rstudio-4.1/rstudio-4.1/resources/userconf
technologies/app/rstudio-4.1/technology.yaml
version.properties

Adding Rstudio 4.1.1

---

technologies/app/dash/dash/context.yaml
technologies/app/dash/metadata.yaml
version.properties

Add dash port to easy install it and avoid create dasg from a custom app

add Dash port

---

technologies/app/kibana-7.15.1/kibana-7.15.1/context.yaml
technologies/app/kibana-7.15.1/metadata.yaml
version.properties

Sdktechno 163

---

technologies/job/python/metadata.yaml
technologies/job/python/python-3.10-base/Dockerfile
technologies/job/python/python-3.10-base/build.gradle.kts
technologies/job/python/python-3.10-base/dockerInfo.yaml
technologies/job/python/python-3.10-base/entrypoint
technologies/job/python/python-3.10-base/image_test.yaml
technologies/job/python/python-3.10/Dockerfile
technologies/job/python/python-3.10/build.gradle.kts
technologies/job/python/python-3.10/context.yaml
technologies/job/python/python-3.10/dockerInfo.yaml
technologies/job/python/python-3.10/image_test.yaml
technologies/job/python/python-3.10/resources/requirements.txt
technologies/job/python/python-3.8/Dockerfile
technologies/job/python/python-3.8/dockerInfo.yaml
technologies/job/python/python-3.8/resources/requirements.txt
technologies/job/python/python-3.9-base/Dockerfile
technologies/job/python/python-3.9-base/dockerInfo.yaml
technologies/job/python/python-3.9/Dockerfile
technologies/job/python/python-3.9/dockerInfo.yaml
technologies/job/python/python-3.9/resources/requirements.txt
version.properties

https://creativedata.atlassian.net/browse/SDKTECHNO-147
Adding Python 3.10

Python 3.10

---

.github/workflows/promote.yml
version.properties

[SDKTECHNO-167] - promote triggered only when PR is merged

---

technologies/job/r/metadata.yaml
technologies/job/r/r-4.1/context.yaml
technologies/job/r/r-4.1/dockerInfo.yaml
technologies/job/r/r-4.1/entrypoint.sh
technologies/job/r/r-4.1/image_test.yaml
version.properties

fix: remove automatic fail when variable is not set

---

technologies/app/jupyter/jupyterlab-base/Dockerfile
technologies/app/jupyter/jupyterlab-base/dockerInfo.yaml
technologies/app/jupyter/jupyterlab-base/entrypoint.sh
technologies/app/jupyter/jupyterlab/dockerInfo.yaml
technologies/app/jupyter/jupyterlab/image_test.yaml
technologies/app/jupyter/metadata.yaml
technologies/job/python/metadata.yaml
technologies/job/python/python-3.10-base/Dockerfile
technologies/job/python/python-3.10-base/dockerInfo.yaml
technologies/job/python/python-3.10-base/entrypoint
technologies/job/python/python-3.10/dockerInfo.yaml
technologies/job/python/python-3.10/image_test.yaml
technologies/job/python/python-3.8-base/Dockerfile
technologies/job/python/python-3.8-base/dockerInfo.yaml
technologies/job/python/python-3.8-base/entrypoint
technologies/job/python/python-3.8/dockerInfo.yaml
technologies/job/python/python-3.8/image_test.yaml
technologies/job/python/python-3.9-base/Dockerfile
technologies/job/python/python-3.9-base/dockerInfo.yaml
technologies/job/python/python-3.9-base/entrypoint
technologies/job/python/python-3.9/dockerInfo.yaml
technologies/job/python/python-3.9/image_test.yaml
version.properties

Sdktechno 169 - Python Hadoop classpath

---

technologies/app/rstudio/metadata.yaml
technologies/app/rstudio/rstudio-4.1/context.yaml
technologies/app/rstudio/rstudio-4.2/Dockerfile
technologies/app/rstudio/rstudio-4.2/build.gradle.kts
technologies/app/rstudio/rstudio-4.2/dockerInfo.yaml
technologies/app/rstudio/rstudio-4.2/image_test.yaml
technologies/job/r/metadata.yaml
technologies/job/r/r-4.1/context.yaml
technologies/job/r/r-4.2/Dockerfile
technologies/job/r/r-4.2/dockerInfo.yaml
technologies/job/r/r-4.2/image_test.yaml
version.properties

Feat: Add odbc in R images

---

technologies/job/r/metadata.yaml
technologies/job/r/r-4.2/dockerInfo.yaml
technologies/job/r/r-4.2/entrypoint.sh
version.properties

[SDKTECHNO-181] R 4.2 fails when R_CUSTOM_CRAN is not present

---

build.gradle.kts
version.properties

[SDKTECHNO-198] change version of technologiesplugin

---

technologies/job/java-scala/java-scala-11/context.yaml
technologies/job/java-scala/java-scala-17/Dockerfile
technologies/job/java-scala/java-scala-17/build.gradle.kts
technologies/job/java-scala/java-scala-17/context.yaml
technologies/job/java-scala/java-scala-17/dockerInfo.yaml
technologies/job/java-scala/java-scala-17/entrypoint
technologies/job/java-scala/java-scala-17/image_test.yaml
technologies/job/java-scala/metadata.yaml
technologies/job/talend/metadata.yaml
technologies/job/talend/talend-Use_Java_11/context.yaml
technologies/job/talend/talend-Use_Java_17/Dockerfile
technologies/job/talend/talend-Use_Java_17/build.gradle.kts
technologies/job/talend/talend-Use_Java_17/context.yaml
technologies/job/talend/talend-Use_Java_17/dockerInfo.yaml
technologies/job/talend/talend-Use_Java_17/entrypoint
technologies/job/talend/talend-Use_Java_17/image_test.yaml
technologies/job/talend/talend-Use_Java_8/dockerInfo.yaml
technologies/job/talend/talend-Use_Java_8/image_test.yaml
version.properties

[SDKTECHNO-195] - Adding Java 17

---

technologies/app/apache-superset/README.md
technologies/app/apache-superset/ReleaseNotes.md
technologies/app/apache-superset/apache-superset-2.0/Dockerfile
technologies/app/apache-superset/apache-superset-2.0/assets/entrypoint.sh
technologies/app/apache-superset/apache-superset-2.0/assets/replace_url.py
technologies/app/apache-superset/apache-superset-2.0/assets/url_fixer.py
technologies/app/apache-superset/apache-superset-2.0/build.gradle.kts
technologies/app/apache-superset/apache-superset-2.0/conf/superset_config.py
technologies/app/apache-superset/apache-superset-2.0/context.yaml
technologies/app/apache-superset/apache-superset-2.0/dockerInfo.yaml
technologies/app/apache-superset/apache-superset-2.0/image_test.yaml
technologies/app/apache-superset/apache-superset-2.0/nginx/server.conf
technologies/app/apache-superset/metadata.yaml
technologies/app/apache-superset/technology.yaml
version.properties

[SDKTECHNO-196] Adding superset 2.0

---

technologies/app/mlflow-server/metadata.yaml
technologies/app/mlflow-server/mlflow-server-2.0/Dockerfile
technologies/app/mlflow-server/mlflow-server-2.0/build.gradle.kts
technologies/app/mlflow-server/mlflow-server-2.0/context.yaml
technologies/app/mlflow-server/mlflow-server-2.0/dockerInfo.yaml
technologies/app/mlflow-server/mlflow-server-2.0/image_test.yaml
technologies/app/mlflow-server/mlflow-server-2.0/resources/entrypoint.sh
version.properties

Sdk techno 194

---

technologies/job/bash/bash-debian11-bullseye-aws/Dockerfile
technologies/job/bash/bash-debian11-bullseye-aws/build.gradle.kts
technologies/job/bash/bash-debian11-bullseye-aws/context.yaml
technologies/job/bash/bash-debian11-bullseye-aws/dockerInfo.yaml
technologies/job/bash/bash-debian11-bullseye-aws/image_test.yaml
technologies/job/bash/bash-debian11-bullseye-azure/Dockerfile
technologies/job/bash/bash-debian11-bullseye-azure/build.gradle.kts
technologies/job/bash/bash-debian11-bullseye-azure/context.yaml
technologies/job/bash/bash-debian11-bullseye-azure/dockerInfo.yaml
technologies/job/bash/bash-debian11-bullseye-azure/image_test.yaml
technologies/job/bash/bash-debian11-bullseye-gcp/Dockerfile
technologies/job/bash/bash-debian11-bullseye-gcp/build.gradle.kts
technologies/job/bash/bash-debian11-bullseye-gcp/context.yaml
technologies/job/bash/bash-debian11-bullseye-gcp/dockerInfo.yaml
technologies/job/bash/bash-debian11-bullseye-gcp/image_test.yaml
technologies/job/bash/bash-debian11-bullseye/Dockerfile
technologies/job/bash/bash-debian11-bullseye/build.gradle.kts
technologies/job/bash/bash-debian11-bullseye/context.yaml
technologies/job/bash/bash-debian11-bullseye/dockerInfo.yaml
technologies/job/bash/bash-debian11-bullseye/entrypoint
technologies/job/bash/bash-debian11-bullseye/image_test.yaml
technologies/job/bash/metadata.yaml
version.properties

[SDKTECHNO-204] Adding Debian 11

---

technologies/app/rstudio/metadata.yaml
technologies/app/rstudio/rstudio-4.1/build.gradle.kts
technologies/app/rstudio/rstudio-4.1/dockerInfo.yaml
technologies/app/rstudio/rstudio-4.1/image_test.yaml
technologies/app/rstudio/rstudio-4.2/build.gradle.kts
technologies/app/rstudio/rstudio-4.2/dockerInfo.yaml
technologies/job/r/metadata.yaml
technologies/job/r/r-4.1/Dockerfile
technologies/job/r/r-4.1/dockerInfo.yaml
technologies/job/r/r-4.2/Dockerfile
technologies/job/r/r-4.2/dockerInfo.yaml
version.properties

Add fixed version of aws.s3 library

---

technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/context.yaml
version.properties

context changes from Experimental to stable

Sdktechno 217 - Modify Saagie Usage Monitoring context

---

technologies/app/saagie-usage-monitoring/README.md
technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/Dockerfile
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/dockerInfo.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/entrypoint.sh
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/grafana/provisioning/alerting/alert.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/update_sqlite.sh
version.properties

Add 3 default alerts for Saagie Usage Monitoring

Sdktechno 216 SUM alerts

---

technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/context.yaml
version.properties

Sdktechno 219

---

technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/context.yaml
technologies/app/saagie-usage-monitoring/technology.yaml

Sdktechno 220

---

technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/dockerInfo.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-3.0/update_sqlite.sh
technologies/app/saagie-usage-monitoring/technology.yaml
version.properties

Don't reset alerts when rebooting SUM

Sdktechno 221

---

technologies/job/gcp-cloud-data-transfer/azure-transfer-jobs/context.yaml
technologies/job/gcp-cloud-data-transfer/metadata.yaml
technologies/job/gcp-cloud-data-transfer/s3-transfer-jobs/context.yaml
technologies/job/gcp-cloud-data-transfer/transfer-jobs/context.yaml
technologies/job/gcp-cloud-data-transfer/tsv-transfer-jobs/context.yaml
technologies/job/gcp-cloud-functions/default/context.yaml
technologies/job/gcp-cloud-functions/metadata.yaml
technologies/job/gcp-dataflow/metadata.yaml
technologies/job/gcp-dataflow/new-job/context.yaml
version.properties

:bug: Sdktechno 226

---

technologies/job/python/metadata.yaml
technologies/job/python/python-3.7/Dockerfile
technologies/job/python/python-3.7/dockerInfo.yaml
technologies/job/python/python-3.7/image_test.yaml
version.properties

Sdktechno 228

---

technologies/job/bash/bash-debian12-bookworm/Dockerfile
technologies/job/bash/bash-debian12-bookworm/build.gradle.kts
technologies/job/bash/bash-debian12-bookworm/context.yaml
technologies/job/bash/bash-debian12-bookworm/dockerInfo.yaml
technologies/job/bash/bash-debian12-bookworm/entrypoint
technologies/job/bash/bash-debian12-bookworm/image_test.yaml
technologies/job/bash/metadata.yaml
version.properties

Sdktechno 231 - Debian 12

---

technologies/job/python/metadata.yaml
technologies/job/python/python-3.7/context.yaml
version.properties

Sdktechno 230

---

version.properties

fix version.properties

---

technologies/app/saagie-usage-monitoring/metadata.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/Dockerfile
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/build.gradle.kts
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/code/__main__.py
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/code/requirements.txt
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/code/utils.py
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/context.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/dockerInfo.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/entrypoint.sh
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana.ini
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/datalake-dashboard.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/datalake-space-explorer.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/s3-dashboard.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/saagie-jobs-conso-dashboard.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/saagie-jobs-failed-timeline.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/dashboards/saagie-jobs-pipelines-dashboard.json
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/provisioning/alerting/alert.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/provisioning/dashboards/all.yml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/grafana/provisioning/datasources/grafana_source_monitoring.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/image_test.yaml
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/infra.sql
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/server.conf
technologies/app/saagie-usage-monitoring/saagie-usage-monitoring-2023.04/update_sqlite.sh
version.properties

Saagie Usage Monitoring 2023.04

Sdktechno 248

---

version.properties

Fix version

---

version.properties

[SDKTECHNO-263] Fix version
